name: Build Flet APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Flet and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet

      - name: Build APK with Flet
        run: |
          flet build apk --yes
        env:
          CI: "true"
          PYTHONUNBUFFERED: "1"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: build/sapk/app-release.apk
